### ISSUE TITLE
Clarification of the real numbers

### ISSUE THREAD

**Issue by rjkilpatrick** [peeterjoot/phy450-relativisticEandM#1]
The real numbers don't contain +/- infinity, but the [extended real numbers](https://en.wikipedia.org/wiki/Extended_real_number_line) do.

https://github.com/peeterjoot/phy450-relativisticEandM/blob/f5c8a8207eb7ffcb7d1be43bd62f4f3102355ff9/lectures/relativisticElectrodynamicsL1.tex#L22-L26

I think it's worth adding a note to reflect this.

Thanks for these notes!

**Comment by peeterjoot** [comment]
Thanks for the feedback.  I've addressed this by avoiding the issue of infinities at the boundary, and just specified that each of the coordinates is a real number.
